### ISSUE TITLE
Setup React.js with Tailwind CSS and Bootstrap

### ISSUE THREAD

**Issue by olisebz** [olisebz/zms-pizza-frontend#1]
React.js Setup:

Install Node.js and npm/yarn.
Create a new React.js project using Create React App or a similar tool.
Familiarize yourself with React's component-based architecture.
Set up routing if necessary using React Router.
Bootstrap Integration:

Install Bootstrap via npm/yarn: npm install bootstrap or yarn add bootstrap.
Import Bootstrap stylesheets into your project.
Utilize Bootstrap's grid system for responsive layouts.
Explore Bootstrap's components and utilities to enhance UI design.
Tailwind CSS Configuration:

Install Tailwind CSS: npm install tailwindcss or yarn add tailwindcss.
Create a Tailwind configuration file using npx tailwindcss init.
Configure Tailwind to purge unused CSS in production builds.
Explore Tailwind's utility-first approach for rapid styling.
Customize Tailwind's default theme to match your project's design system.

**Comment by ymeichtry** [comment]
In "git remote add origin https://github.com/olisebz/zms-pizza-frontend.git" we have a standing React.js page
