### ISSUE TITLE
Add-liscence-file

### ISSUE THREAD

**Issue by ymeichtry** [olisebz/zms-pizza-frontend#14]
We should add a license file. What will we use? That can still be discussed, but we think a MIT-License is perfect.

**Comment by Ehmkayel** [comment]
@ymeichtry I am interested and be glad if you can assign it to me

**Comment by ymeichtry** [comment]
> @ymeichtry I am interested and be glad if you can assign it to me

Hi @Ehmkayel I have assigned you. 
You can make a new Branch and make an "MIT License".
Thanks for collaborating with us!

**Comment by Ehmkayel** [comment]
@ymeichtry Thank you
