### ISSUE TITLE
translate-admin-page-into-english

### ISSUE THREAD

**Issue by ymeichtry** [olisebz/zms-pizza-frontend#4]
The /admin page is still written in german we have to change the HTML stuff to english

**Comment by SeanAverS** [comment]
Hello, 

I'm interested on working on this. Could I please be assigned? Thanks.

**Comment by ymeichtry** [comment]
Thank you @SeanAverS for solving this Issue / making this story. We look forward to work with you :)
PS: I will close this Issue
